# WARNING: This file is autogenerated by @atomic-ehr/codegen.
# GitHub: https://github.com/atomic-ehr/codegen
# Any manual changes made to this file may be overwritten.

from __future__ import annotations
from pydantic import BaseModel, ConfigDict, Field, PositiveInt
from typing import List as PyList, Literal

from fhir_types.hl7_fhir_r4_core.base import Narrative
from fhir_types.hl7_fhir_r4_core.resource import Resource
from fhir_types.hl7_fhir_r4_core.resource_families import ResourceFamily


class DomainResource(Resource):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    resource_type: str = Field(
        default='DomainResource',
        alias='resourceType',
        serialization_alias='resourceType',
        frozen=True,
        pattern='DomainResource'
    )
    contained: PyList[ResourceFamily] | None = Field(None, alias="contained", serialization_alias="contained")
    text: Narrative | None = Field(None, alias="text", serialization_alias="text")

    def to_json(self, indent: int | None = None) -> str:
        return self.model_dump_json(exclude_unset=True, exclude_none=True, indent=indent)

    @classmethod
    def from_json(cls, json: str) -> DomainResource:
        return cls.model_validate_json(json)

