// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { CodeableConcept } from "../../hl7-fhir-r4-core/CodeableConcept";
import type { Extension } from "../../hl7-fhir-r4-core/Extension";

export type USCoreTribalAffiliationExtension_Extension_TribalAffiliationSliceFlat = Omit<Extension, "url" | "value" | "valueBase64Binary" | "valueBoolean" | "valueCanonical" | "valueCode" | "valueDate" | "valueDateTime" | "valueDecimal" | "valueId" | "valueInstant" | "valueInteger" | "valueMarkdown" | "valueOid" | "valuePositiveInt" | "valueString" | "valueTime" | "valueUnsignedInt" | "valueUri" | "valueUrl" | "valueUuid" | "valueAddress" | "valueAge" | "valueAnnotation" | "valueAttachment" | "valueCodeableConcept" | "valueCoding" | "valueContactPoint" | "valueCount" | "valueDistance" | "valueDuration" | "valueHumanName" | "valueIdentifier" | "valueMoney" | "valuePeriod" | "valueQuantity" | "valueRange" | "valueRatio" | "valueReference" | "valueSampledData" | "valueSignature" | "valueTiming" | "valueContactDetail" | "valueContributor" | "valueDataRequirement" | "valueExpression" | "valueParameterDefinition" | "valueRelatedArtifact" | "valueTriggerDefinition" | "valueUsageContext" | "valueDosage" | "valueMeta"> & CodeableConcept;
export type USCoreTribalAffiliationExtension_Extension_IsEnrolledSliceFlat = Omit<Extension, "url">;

import {
    buildResource,
    isRawExtensionInput,
    applySliceMatch,
    matchesValue,
    setArraySlice,
    getArraySlice,
    ensureSliceDefaults,
    stripMatchKeys,
    wrapSliceChoice,
    unwrapSliceChoice,
    isExtension,
    getExtensionValue,
    pushExtension,
    validateRequired,
    validateExcluded,
    validateFixedValue,
    validateSliceCardinality,
    validateEnum,
    validateReference,
    validateChoiceRequired,
    validateMustSupport,
} from "../../profile-helpers";

export type USCoreTribalAffiliationExtensionProfileRaw = {
    extension?: Extension[];
}

export type USCoreTribalAffiliationExtensionProfileFlat = {
    tribalAffiliation: CodeableConcept;
    isEnrolled?: boolean;
}

// CanonicalURL: http://hl7.org/fhir/us/core/StructureDefinition/us-core-tribal-affiliation (pkg: hl7.fhir.us.core#8.0.1)
export class USCoreTribalAffiliationExtensionProfile {
    static readonly canonicalUrl = "http://hl7.org/fhir/us/core/StructureDefinition/us-core-tribal-affiliation";

    private static readonly tribalAffiliationSliceMatch: Record<string, unknown> = {"url":"tribalAffiliation"};
    private static readonly isEnrolledSliceMatch: Record<string, unknown> = {"url":"isEnrolled"};

    private resource: Extension;

    constructor (resource: Extension) {
        this.resource = resource;
    }

    static from (resource: Extension) : USCoreTribalAffiliationExtensionProfile {
        const profile = new USCoreTribalAffiliationExtensionProfile(resource);
        const { errors } = profile.validate();
        if (errors.length > 0) throw new Error(errors.join("; "))
        return profile;
    }

    static apply (resource: Extension) : USCoreTribalAffiliationExtensionProfile {
        return new USCoreTribalAffiliationExtensionProfile(resource);
    }

    private static resolveInput (args: USCoreTribalAffiliationExtensionProfileRaw | USCoreTribalAffiliationExtensionProfileFlat) : Extension[] {
        if (isRawExtensionInput<USCoreTribalAffiliationExtensionProfileRaw>(args)) {
            return args.extension ?? [];
        } else {
            const result: Extension[] = [];
            if (args.tribalAffiliation !== undefined) {
                result.push({ url: "tribalAffiliation", valueCodeableConcept: args.tribalAffiliation } as Extension);
            }
            if (args.isEnrolled !== undefined) {
                result.push({ url: "isEnrolled", valueBoolean: args.isEnrolled } as Extension);
            }
            return result;
        }
    }

    static createResource (args: USCoreTribalAffiliationExtensionProfileRaw | USCoreTribalAffiliationExtensionProfileFlat) : Extension {
        const resolvedExtensions = USCoreTribalAffiliationExtensionProfile.resolveInput(args ?? {});
        const extensionWithDefaults = ensureSliceDefaults(
            resolvedExtensions,
            USCoreTribalAffiliationExtensionProfile.tribalAffiliationSliceMatch,
        );

        const resource = buildResource<Extension>( {
            url: "http://hl7.org/fhir/us/core/StructureDefinition/us-core-tribal-affiliation",
            extension: extensionWithDefaults,
        })
        return resource;
    }

    static create (args: USCoreTribalAffiliationExtensionProfileRaw | USCoreTribalAffiliationExtensionProfileFlat) : USCoreTribalAffiliationExtensionProfile {
        return USCoreTribalAffiliationExtensionProfile.apply(USCoreTribalAffiliationExtensionProfile.createResource(args));
    }

    toResource () : Extension {
        return this.resource;
    }

    // Field accessors
    getExtension () : Extension[] | undefined {
        return this.resource.extension as Extension[] | undefined;
    }

    setExtension (value: Extension[]) : this {
        Object.assign(this.resource, { extension: value });
        return this;
    }

    getUrl () : string | undefined {
        return this.resource.url as string | undefined;
    }

    setUrl (value: string) : this {
        Object.assign(this.resource, { url: value });
        return this;
    }

    // Extensions
    public setTribalAffiliation (value: Omit<Extension, "url"> | Extension): this {
        if (isExtension(value)) {
            if (value.url !== "tribalAffiliation") throw new Error(`Expected extension url 'tribalAffiliation', got '${value.url}'`)
            pushExtension(this.resource, value)
        } else {
            pushExtension(this.resource, { url: "tribalAffiliation", ...value } as Extension)
        }
        return this
    }

    public getTribalAffiliation (): Extension | undefined {
        return this.resource.extension?.find(e => e.url === "tribalAffiliation")
    }

    public setIsEnrolled (value: Omit<Extension, "url"> | Extension): this {
        if (isExtension(value)) {
            if (value.url !== "isEnrolled") throw new Error(`Expected extension url 'isEnrolled', got '${value.url}'`)
            pushExtension(this.resource, value)
        } else {
            pushExtension(this.resource, { url: "isEnrolled", ...value } as Extension)
        }
        return this
    }

    public getIsEnrolled (): Extension | undefined {
        return this.resource.extension?.find(e => e.url === "isEnrolled")
    }

    // Slices
    public setExtensionTribalAffiliation (input?: USCoreTribalAffiliationExtension_Extension_TribalAffiliationSliceFlat | Extension): this {
        const match = USCoreTribalAffiliationExtensionProfile.tribalAffiliationSliceMatch
        if (input && matchesValue(input, match)) {
            setArraySlice(this.resource.extension ??= [], match, input as Extension)
            return this
        }
        const wrapped = wrapSliceChoice<Extension>(input ?? {}, "valueCodeableConcept")
        const value = applySliceMatch<Extension>(wrapped, match)
        setArraySlice(this.resource.extension ??= [], match, value)
        return this
    }

    public setExtensionIsEnrolled (input?: USCoreTribalAffiliationExtension_Extension_IsEnrolledSliceFlat | Extension): this {
        const match = USCoreTribalAffiliationExtensionProfile.isEnrolledSliceMatch
        if (input && matchesValue(input, match)) {
            setArraySlice(this.resource.extension ??= [], match, input as Extension)
            return this
        }
        const value = applySliceMatch<Extension>(input ?? {}, match)
        setArraySlice(this.resource.extension ??= [], match, value)
        return this
    }

    public getExtensionTribalAffiliation(mode: 'flat'): USCoreTribalAffiliationExtension_Extension_TribalAffiliationSliceFlat | undefined;
    public getExtensionTribalAffiliation(mode: 'raw'): Extension | undefined;
    public getExtensionTribalAffiliation(): USCoreTribalAffiliationExtension_Extension_TribalAffiliationSliceFlat | undefined;
    public getExtensionTribalAffiliation (mode: 'flat' | 'raw' = 'flat'): USCoreTribalAffiliationExtension_Extension_TribalAffiliationSliceFlat | Extension | undefined {
        const match = USCoreTribalAffiliationExtensionProfile.tribalAffiliationSliceMatch
        const item = getArraySlice(this.resource.extension, match)
        if (!item) return undefined
        if (mode === 'raw') return item
        return unwrapSliceChoice<USCoreTribalAffiliationExtension_Extension_TribalAffiliationSliceFlat>(item, ["url"], "valueCodeableConcept")
    }

    public getExtensionIsEnrolled(mode: 'flat'): USCoreTribalAffiliationExtension_Extension_IsEnrolledSliceFlat | undefined;
    public getExtensionIsEnrolled(mode: 'raw'): Extension | undefined;
    public getExtensionIsEnrolled(): USCoreTribalAffiliationExtension_Extension_IsEnrolledSliceFlat | undefined;
    public getExtensionIsEnrolled (mode: 'flat' | 'raw' = 'flat'): USCoreTribalAffiliationExtension_Extension_IsEnrolledSliceFlat | Extension | undefined {
        const match = USCoreTribalAffiliationExtensionProfile.isEnrolledSliceMatch
        const item = getArraySlice(this.resource.extension, match)
        if (!item) return undefined
        if (mode === 'raw') return item
        return stripMatchKeys<USCoreTribalAffiliationExtension_Extension_IsEnrolledSliceFlat>(item, ["url"])
    }

    // Validation
    validate(): { errors: string[]; warnings: string[] } {
        const profileName = "USCoreTribalAffiliationExtension"
        const res = this.resource
        return {
            errors: [
                ...validateRequired(res, profileName, "extension"),
                ...validateSliceCardinality(res, profileName, "extension", {"url":"tribalAffiliation"}, "tribalAffiliation", 1, 1),
                ...validateSliceCardinality(res, profileName, "extension", {"url":"isEnrolled"}, "isEnrolled", 0, 1),
                ...validateRequired(res, profileName, "url"),
                ...validateFixedValue(res, profileName, "url", USCoreTribalAffiliationExtensionProfile.canonicalUrl),
            ],
            warnings: [],
        }
    }

}

