// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { Coding } from "../../hl7-fhir-r4-core/Coding";
import type { Extension } from "../../hl7-fhir-r4-core/Extension";

export type USCoreEthnicityExtension_Extension_OmbCategorySliceFlat = Omit<Extension, "url" | "value" | "valueBase64Binary" | "valueBoolean" | "valueCanonical" | "valueCode" | "valueDate" | "valueDateTime" | "valueDecimal" | "valueId" | "valueInstant" | "valueInteger" | "valueMarkdown" | "valueOid" | "valuePositiveInt" | "valueString" | "valueTime" | "valueUnsignedInt" | "valueUri" | "valueUrl" | "valueUuid" | "valueAddress" | "valueAge" | "valueAnnotation" | "valueAttachment" | "valueCodeableConcept" | "valueCoding" | "valueContactPoint" | "valueCount" | "valueDistance" | "valueDuration" | "valueHumanName" | "valueIdentifier" | "valueMoney" | "valuePeriod" | "valueQuantity" | "valueRange" | "valueRatio" | "valueReference" | "valueSampledData" | "valueSignature" | "valueTiming" | "valueContactDetail" | "valueContributor" | "valueDataRequirement" | "valueExpression" | "valueParameterDefinition" | "valueRelatedArtifact" | "valueTriggerDefinition" | "valueUsageContext" | "valueDosage" | "valueMeta"> & Coding;
export type USCoreEthnicityExtension_Extension_DetailedSliceFlat = Omit<Extension, "url" | "value" | "valueBase64Binary" | "valueBoolean" | "valueCanonical" | "valueCode" | "valueDate" | "valueDateTime" | "valueDecimal" | "valueId" | "valueInstant" | "valueInteger" | "valueMarkdown" | "valueOid" | "valuePositiveInt" | "valueString" | "valueTime" | "valueUnsignedInt" | "valueUri" | "valueUrl" | "valueUuid" | "valueAddress" | "valueAge" | "valueAnnotation" | "valueAttachment" | "valueCodeableConcept" | "valueCoding" | "valueContactPoint" | "valueCount" | "valueDistance" | "valueDuration" | "valueHumanName" | "valueIdentifier" | "valueMoney" | "valuePeriod" | "valueQuantity" | "valueRange" | "valueRatio" | "valueReference" | "valueSampledData" | "valueSignature" | "valueTiming" | "valueContactDetail" | "valueContributor" | "valueDataRequirement" | "valueExpression" | "valueParameterDefinition" | "valueRelatedArtifact" | "valueTriggerDefinition" | "valueUsageContext" | "valueDosage" | "valueMeta"> & Coding;
export type USCoreEthnicityExtension_Extension_TextSliceFlat = Omit<Extension, "url">;

import {
    buildResource,
    isRawExtensionInput,
    applySliceMatch,
    matchesValue,
    setArraySlice,
    getArraySlice,
    ensureSliceDefaults,
    stripMatchKeys,
    wrapSliceChoice,
    unwrapSliceChoice,
    isExtension,
    getExtensionValue,
    pushExtension,
    validateRequired,
    validateExcluded,
    validateFixedValue,
    validateSliceCardinality,
    validateEnum,
    validateReference,
    validateChoiceRequired,
    validateMustSupport,
} from "../../profile-helpers";

export type USCoreEthnicityExtensionProfileRaw = {
    extension?: Extension[];
}

export type USCoreEthnicityExtensionProfileFlat = {
    ombCategory?: Coding;
    detailed?: Coding[];
    text: string;
}

// CanonicalURL: http://hl7.org/fhir/us/core/StructureDefinition/us-core-ethnicity (pkg: hl7.fhir.us.core#8.0.1)
export class USCoreEthnicityExtensionProfile {
    static readonly canonicalUrl = "http://hl7.org/fhir/us/core/StructureDefinition/us-core-ethnicity";

    private static readonly ombCategorySliceMatch: Record<string, unknown> = {"url":"ombCategory"};
    private static readonly detailedSliceMatch: Record<string, unknown> = {"url":"detailed"};
    private static readonly textSliceMatch: Record<string, unknown> = {"url":"text"};

    private resource: Extension;

    constructor (resource: Extension) {
        this.resource = resource;
    }

    static from (resource: Extension) : USCoreEthnicityExtensionProfile {
        const profile = new USCoreEthnicityExtensionProfile(resource);
        const { errors } = profile.validate();
        if (errors.length > 0) throw new Error(errors.join("; "))
        return profile;
    }

    static apply (resource: Extension) : USCoreEthnicityExtensionProfile {
        return new USCoreEthnicityExtensionProfile(resource);
    }

    private static resolveInput (args: USCoreEthnicityExtensionProfileRaw | USCoreEthnicityExtensionProfileFlat) : Extension[] {
        if (isRawExtensionInput<USCoreEthnicityExtensionProfileRaw>(args)) {
            return args.extension ?? [];
        } else {
            const result: Extension[] = [];
            if (args.ombCategory !== undefined) {
                result.push({ url: "ombCategory", valueCoding: args.ombCategory } as Extension);
            }
            if (args.detailed) {
                for (const item of args.detailed) {
                    result.push({ url: "detailed", valueCoding: item } as Extension);
                }
            }
            if (args.text !== undefined) {
                result.push({ url: "text", valueString: args.text } as Extension);
            }
            return result;
        }
    }

    static createResource (args: USCoreEthnicityExtensionProfileRaw | USCoreEthnicityExtensionProfileFlat) : Extension {
        const resolvedExtensions = USCoreEthnicityExtensionProfile.resolveInput(args ?? {});
        const extensionWithDefaults = ensureSliceDefaults(
            resolvedExtensions,
            USCoreEthnicityExtensionProfile.textSliceMatch,
        );

        const resource = buildResource<Extension>( {
            url: "http://hl7.org/fhir/us/core/StructureDefinition/us-core-ethnicity",
            extension: extensionWithDefaults,
        })
        return resource;
    }

    static create (args: USCoreEthnicityExtensionProfileRaw | USCoreEthnicityExtensionProfileFlat) : USCoreEthnicityExtensionProfile {
        return USCoreEthnicityExtensionProfile.apply(USCoreEthnicityExtensionProfile.createResource(args));
    }

    toResource () : Extension {
        return this.resource;
    }

    // Field accessors
    getExtension () : Extension[] | undefined {
        return this.resource.extension as Extension[] | undefined;
    }

    setExtension (value: Extension[]) : this {
        Object.assign(this.resource, { extension: value });
        return this;
    }

    getUrl () : string | undefined {
        return this.resource.url as string | undefined;
    }

    setUrl (value: string) : this {
        Object.assign(this.resource, { url: value });
        return this;
    }

    // Extensions
    public setOmbCategory (value: Omit<Extension, "url"> | Extension): this {
        if (isExtension(value)) {
            if (value.url !== "ombCategory") throw new Error(`Expected extension url 'ombCategory', got '${value.url}'`)
            pushExtension(this.resource, value)
        } else {
            pushExtension(this.resource, { url: "ombCategory", ...value } as Extension)
        }
        return this
    }

    public getOmbCategory (): Extension | undefined {
        return this.resource.extension?.find(e => e.url === "ombCategory")
    }

    public setDetailed (value: Omit<Extension, "url"> | Extension): this {
        if (isExtension(value)) {
            if (value.url !== "detailed") throw new Error(`Expected extension url 'detailed', got '${value.url}'`)
            pushExtension(this.resource, value)
        } else {
            pushExtension(this.resource, { url: "detailed", ...value } as Extension)
        }
        return this
    }

    public getDetailed (): Extension | undefined {
        return this.resource.extension?.find(e => e.url === "detailed")
    }

    public setText (value: Omit<Extension, "url"> | Extension): this {
        if (isExtension(value)) {
            if (value.url !== "text") throw new Error(`Expected extension url 'text', got '${value.url}'`)
            pushExtension(this.resource, value)
        } else {
            pushExtension(this.resource, { url: "text", ...value } as Extension)
        }
        return this
    }

    public getText (): Extension | undefined {
        return this.resource.extension?.find(e => e.url === "text")
    }

    // Slices
    public setExtensionOmbCategory (input?: USCoreEthnicityExtension_Extension_OmbCategorySliceFlat | Extension): this {
        const match = USCoreEthnicityExtensionProfile.ombCategorySliceMatch
        if (input && matchesValue(input, match)) {
            setArraySlice(this.resource.extension ??= [], match, input as Extension)
            return this
        }
        const wrapped = wrapSliceChoice<Extension>(input ?? {}, "valueCoding")
        const value = applySliceMatch<Extension>(wrapped, match)
        setArraySlice(this.resource.extension ??= [], match, value)
        return this
    }

    public setExtensionDetailed (input?: USCoreEthnicityExtension_Extension_DetailedSliceFlat | Extension): this {
        const match = USCoreEthnicityExtensionProfile.detailedSliceMatch
        if (input && matchesValue(input, match)) {
            setArraySlice(this.resource.extension ??= [], match, input as Extension)
            return this
        }
        const wrapped = wrapSliceChoice<Extension>(input ?? {}, "valueCoding")
        const value = applySliceMatch<Extension>(wrapped, match)
        setArraySlice(this.resource.extension ??= [], match, value)
        return this
    }

    public setExtensionText (input?: USCoreEthnicityExtension_Extension_TextSliceFlat | Extension): this {
        const match = USCoreEthnicityExtensionProfile.textSliceMatch
        if (input && matchesValue(input, match)) {
            setArraySlice(this.resource.extension ??= [], match, input as Extension)
            return this
        }
        const value = applySliceMatch<Extension>(input ?? {}, match)
        setArraySlice(this.resource.extension ??= [], match, value)
        return this
    }

    public getExtensionOmbCategory(mode: 'flat'): USCoreEthnicityExtension_Extension_OmbCategorySliceFlat | undefined;
    public getExtensionOmbCategory(mode: 'raw'): Extension | undefined;
    public getExtensionOmbCategory(): USCoreEthnicityExtension_Extension_OmbCategorySliceFlat | undefined;
    public getExtensionOmbCategory (mode: 'flat' | 'raw' = 'flat'): USCoreEthnicityExtension_Extension_OmbCategorySliceFlat | Extension | undefined {
        const match = USCoreEthnicityExtensionProfile.ombCategorySliceMatch
        const item = getArraySlice(this.resource.extension, match)
        if (!item) return undefined
        if (mode === 'raw') return item
        return unwrapSliceChoice<USCoreEthnicityExtension_Extension_OmbCategorySliceFlat>(item, ["url"], "valueCoding")
    }

    public getExtensionDetailed(mode: 'flat'): USCoreEthnicityExtension_Extension_DetailedSliceFlat | undefined;
    public getExtensionDetailed(mode: 'raw'): Extension | undefined;
    public getExtensionDetailed(): USCoreEthnicityExtension_Extension_DetailedSliceFlat | undefined;
    public getExtensionDetailed (mode: 'flat' | 'raw' = 'flat'): USCoreEthnicityExtension_Extension_DetailedSliceFlat | Extension | undefined {
        const match = USCoreEthnicityExtensionProfile.detailedSliceMatch
        const item = getArraySlice(this.resource.extension, match)
        if (!item) return undefined
        if (mode === 'raw') return item
        return unwrapSliceChoice<USCoreEthnicityExtension_Extension_DetailedSliceFlat>(item, ["url"], "valueCoding")
    }

    public getExtensionText(mode: 'flat'): USCoreEthnicityExtension_Extension_TextSliceFlat | undefined;
    public getExtensionText(mode: 'raw'): Extension | undefined;
    public getExtensionText(): USCoreEthnicityExtension_Extension_TextSliceFlat | undefined;
    public getExtensionText (mode: 'flat' | 'raw' = 'flat'): USCoreEthnicityExtension_Extension_TextSliceFlat | Extension | undefined {
        const match = USCoreEthnicityExtensionProfile.textSliceMatch
        const item = getArraySlice(this.resource.extension, match)
        if (!item) return undefined
        if (mode === 'raw') return item
        return stripMatchKeys<USCoreEthnicityExtension_Extension_TextSliceFlat>(item, ["url"])
    }

    // Validation
    validate(): { errors: string[]; warnings: string[] } {
        const profileName = "USCoreEthnicityExtension"
        const res = this.resource
        return {
            errors: [
                ...validateRequired(res, profileName, "extension"),
                ...validateSliceCardinality(res, profileName, "extension", {"url":"ombCategory"}, "ombCategory", 0, 1),
                ...validateSliceCardinality(res, profileName, "extension", {"url":"text"}, "text", 1, 1),
                ...validateRequired(res, profileName, "url"),
                ...validateFixedValue(res, profileName, "url", USCoreEthnicityExtensionProfile.canonicalUrl),
            ],
            warnings: [],
        }
    }

}

