// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { Element } from "../hl7-fhir-r4-core/Element";
import type { Period } from "../hl7-fhir-r4-core/Period";

export type { Element } from "../hl7-fhir-r4-core/Element";
export type { Period } from "../hl7-fhir-r4-core/Period";

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/Address (pkg: hl7.fhir.r4.core#4.0.1)
export interface Address extends Element {
    city?: string;
    country?: string;
    district?: string;
    line?: string[];
    period?: Period;
    postalCode?: string;
    state?: string;
    text?: string;
    type?: ("postal" | "physical" | "both");
    use?: ("home" | "work" | "temp" | "old" | "billing");
}
