// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { Element } from "../hl7-fhir-r4-core/Element";

export type { Element } from "../hl7-fhir-r4-core/Element";

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/ParameterDefinition (pkg: hl7.fhir.r4.core#4.0.1)
export interface ParameterDefinition extends Element {
    documentation?: string;
    max?: string;
    min?: number;
    name?: string;
    profile?: string;
    type: string;
    use: ("in" | "out");
}
