// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { CodeableConcept } from "../../hl7-fhir-r4-core/CodeableConcept";
import type { Observation, ObservationComponent } from "../../hl7-fhir-r4-core/Observation";
import type { Period } from "../../hl7-fhir-r4-core/Period";
import type { Quantity } from "../../hl7-fhir-r4-core/Quantity";
import type { Reference } from "../../hl7-fhir-r4-core/Reference";

export type Observation_bp_Category_VSCatSliceFlat = Omit<CodeableConcept, "coding">;
export type Observation_bp_Component_SystolicBPSliceFlat = Omit<ObservationComponent, "code" | "value" | "valueQuantity" | "valueCodeableConcept" | "valueString" | "valueBoolean" | "valueInteger" | "valueRange" | "valueRatio" | "valueSampledData" | "valueTime" | "valueDateTime" | "valuePeriod"> & Quantity;
export type Observation_bp_Component_DiastolicBPSliceFlat = Omit<ObservationComponent, "code" | "value" | "valueQuantity" | "valueCodeableConcept" | "valueString" | "valueBoolean" | "valueInteger" | "valueRange" | "valueRatio" | "valueSampledData" | "valueTime" | "valueDateTime" | "valuePeriod"> & Quantity;

import {
    buildResource,
    ensureProfile,
    applySliceMatch,
    matchesValue,
    setArraySlice,
    getArraySlice,
    ensureSliceDefaults,
    stripMatchKeys,
    wrapSliceChoice,
    unwrapSliceChoice,
    validateRequired,
    validateExcluded,
    validateFixedValue,
    validateSliceCardinality,
    validateEnum,
    validateReference,
    validateChoiceRequired,
    validateMustSupport,
} from "../../profile-helpers";

export type observation_bpProfileRaw = {
    status: ("registered" | "preliminary" | "final" | "amended" | "corrected" | "cancelled" | "entered-in-error" | "unknown");
    subject: Reference<"Patient">;
    category?: CodeableConcept<("social-history" | "vital-signs" | "imaging" | "laboratory" | "procedure" | "survey" | "exam" | "therapy" | "activity" | string)>[];
    component?: ObservationComponent[];
}

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/bp (pkg: hl7.fhir.r4.core#4.0.1)
export class observation_bpProfile {
    static readonly canonicalUrl = "http://hl7.org/fhir/StructureDefinition/bp";

    private static readonly VSCatSliceMatch: Record<string, unknown> = {"coding":{"code":"vital-signs","system":"http://terminology.hl7.org/CodeSystem/observation-category"}};
    private static readonly SystolicBPSliceMatch: Record<string, unknown> = {"code":{"coding":{"code":"8480-6","system":"http://loinc.org"}}};
    private static readonly DiastolicBPSliceMatch: Record<string, unknown> = {"code":{"coding":{"code":"8462-4","system":"http://loinc.org"}}};

    private resource: Observation;

    constructor (resource: Observation) {
        this.resource = resource;
    }

    static from (resource: Observation) : observation_bpProfile {
        if (!resource.meta?.profile?.includes(observation_bpProfile.canonicalUrl)) {
            throw new Error(`observation_bpProfile: meta.profile must include ${observation_bpProfile.canonicalUrl}`)
        }
        const profile = new observation_bpProfile(resource);
        const { errors } = profile.validate();
        if (errors.length > 0) throw new Error(errors.join("; "))
        return profile;
    }

    static apply (resource: Observation) : observation_bpProfile {
        ensureProfile(resource, observation_bpProfile.canonicalUrl);
        return new observation_bpProfile(resource);
    }

    static createResource (args: observation_bpProfileRaw) : Observation {
        const categoryWithDefaults = ensureSliceDefaults(
            [...(args.category ?? [])],
            observation_bpProfile.VSCatSliceMatch,
        );
        const componentWithDefaults = ensureSliceDefaults(
            [...(args.component ?? [])],
            observation_bpProfile.SystolicBPSliceMatch,
            observation_bpProfile.DiastolicBPSliceMatch,
        );

        const resource = buildResource<Observation>( {
            resourceType: "Observation",
            code: {"coding":[{"code":"85354-9","system":"http://loinc.org"}]},
            category: categoryWithDefaults,
            component: componentWithDefaults,
            status: args.status,
            subject: args.subject,
            meta: { profile: [observation_bpProfile.canonicalUrl] },
        })
        return resource;
    }

    static create (args: observation_bpProfileRaw) : observation_bpProfile {
        return observation_bpProfile.apply(observation_bpProfile.createResource(args));
    }

    toResource () : Observation {
        return this.resource;
    }

    // Field accessors
    getStatus () : ("registered" | "preliminary" | "final" | "amended" | "corrected" | "cancelled" | "entered-in-error" | "unknown") | undefined {
        return this.resource.status as ("registered" | "preliminary" | "final" | "amended" | "corrected" | "cancelled" | "entered-in-error" | "unknown") | undefined;
    }

    setStatus (value: ("registered" | "preliminary" | "final" | "amended" | "corrected" | "cancelled" | "entered-in-error" | "unknown")) : this {
        Object.assign(this.resource, { status: value });
        return this;
    }

    getSubject () : Reference<"Patient"> | undefined {
        return this.resource.subject as Reference<"Patient"> | undefined;
    }

    setSubject (value: Reference<"Patient">) : this {
        Object.assign(this.resource, { subject: value });
        return this;
    }

    getCategory () : CodeableConcept<("social-history" | "vital-signs" | "imaging" | "laboratory" | "procedure" | "survey" | "exam" | "therapy" | "activity" | string)>[] | undefined {
        return this.resource.category as CodeableConcept<("social-history" | "vital-signs" | "imaging" | "laboratory" | "procedure" | "survey" | "exam" | "therapy" | "activity" | string)>[] | undefined;
    }

    setCategory (value: CodeableConcept<("social-history" | "vital-signs" | "imaging" | "laboratory" | "procedure" | "survey" | "exam" | "therapy" | "activity" | string)>[]) : this {
        Object.assign(this.resource, { category: value });
        return this;
    }

    getCode () : CodeableConcept<("85353-1" | "9279-1" | "8867-4" | "2708-6" | "8310-5" | "8302-2" | "9843-4" | "29463-7" | "39156-5" | "85354-9" | "8480-6" | "8462-4" | "8478-0" | string)> | undefined {
        return this.resource.code as CodeableConcept<("85353-1" | "9279-1" | "8867-4" | "2708-6" | "8310-5" | "8302-2" | "9843-4" | "29463-7" | "39156-5" | "85354-9" | "8480-6" | "8462-4" | "8478-0" | string)> | undefined;
    }

    setCode (value: CodeableConcept<("85353-1" | "9279-1" | "8867-4" | "2708-6" | "8310-5" | "8302-2" | "9843-4" | "29463-7" | "39156-5" | "85354-9" | "8480-6" | "8462-4" | "8478-0" | string)>) : this {
        Object.assign(this.resource, { code: value });
        return this;
    }

    getComponent () : ObservationComponent[] | undefined {
        return this.resource.component as ObservationComponent[] | undefined;
    }

    setComponent (value: ObservationComponent[]) : this {
        Object.assign(this.resource, { component: value });
        return this;
    }

    getEffectiveDateTime () : string | undefined {
        return this.resource.effectiveDateTime as string | undefined;
    }

    setEffectiveDateTime (value: string) : this {
        Object.assign(this.resource, { effectiveDateTime: value });
        return this;
    }

    getEffectivePeriod () : Period | undefined {
        return this.resource.effectivePeriod as Period | undefined;
    }

    setEffectivePeriod (value: Period) : this {
        Object.assign(this.resource, { effectivePeriod: value });
        return this;
    }

    getValueQuantity () : Quantity | undefined {
        return this.resource.valueQuantity as Quantity | undefined;
    }

    setValueQuantity (value: Quantity) : this {
        Object.assign(this.resource, { valueQuantity: value });
        return this;
    }

    // Extensions
    // Slices
    public setVSCat (input?: Observation_bp_Category_VSCatSliceFlat | CodeableConcept): this {
        const match = observation_bpProfile.VSCatSliceMatch
        if (input && matchesValue(input, match)) {
            setArraySlice(this.resource.category ??= [], match, input as CodeableConcept)
            return this
        }
        const value = applySliceMatch<CodeableConcept>(input ?? {}, match)
        setArraySlice(this.resource.category ??= [], match, value)
        return this
    }

    public setSystolicBP (input?: Observation_bp_Component_SystolicBPSliceFlat | ObservationComponent): this {
        const match = observation_bpProfile.SystolicBPSliceMatch
        if (input && matchesValue(input, match)) {
            setArraySlice(this.resource.component ??= [], match, input as ObservationComponent)
            return this
        }
        const wrapped = wrapSliceChoice<ObservationComponent>(input ?? {}, "valueQuantity")
        const value = applySliceMatch<ObservationComponent>(wrapped, match)
        setArraySlice(this.resource.component ??= [], match, value)
        return this
    }

    public setDiastolicBP (input?: Observation_bp_Component_DiastolicBPSliceFlat | ObservationComponent): this {
        const match = observation_bpProfile.DiastolicBPSliceMatch
        if (input && matchesValue(input, match)) {
            setArraySlice(this.resource.component ??= [], match, input as ObservationComponent)
            return this
        }
        const wrapped = wrapSliceChoice<ObservationComponent>(input ?? {}, "valueQuantity")
        const value = applySliceMatch<ObservationComponent>(wrapped, match)
        setArraySlice(this.resource.component ??= [], match, value)
        return this
    }

    public getVSCat(mode: 'flat'): Observation_bp_Category_VSCatSliceFlat | undefined;
    public getVSCat(mode: 'raw'): CodeableConcept | undefined;
    public getVSCat(): Observation_bp_Category_VSCatSliceFlat | undefined;
    public getVSCat (mode: 'flat' | 'raw' = 'flat'): Observation_bp_Category_VSCatSliceFlat | CodeableConcept | undefined {
        const match = observation_bpProfile.VSCatSliceMatch
        const item = getArraySlice(this.resource.category, match)
        if (!item) return undefined
        if (mode === 'raw') return item
        return stripMatchKeys<Observation_bp_Category_VSCatSliceFlat>(item, ["coding"])
    }

    public getSystolicBP(mode: 'flat'): Observation_bp_Component_SystolicBPSliceFlat | undefined;
    public getSystolicBP(mode: 'raw'): ObservationComponent | undefined;
    public getSystolicBP(): Observation_bp_Component_SystolicBPSliceFlat | undefined;
    public getSystolicBP (mode: 'flat' | 'raw' = 'flat'): Observation_bp_Component_SystolicBPSliceFlat | ObservationComponent | undefined {
        const match = observation_bpProfile.SystolicBPSliceMatch
        const item = getArraySlice(this.resource.component, match)
        if (!item) return undefined
        if (mode === 'raw') return item
        return unwrapSliceChoice<Observation_bp_Component_SystolicBPSliceFlat>(item, ["code"], "valueQuantity")
    }

    public getDiastolicBP(mode: 'flat'): Observation_bp_Component_DiastolicBPSliceFlat | undefined;
    public getDiastolicBP(mode: 'raw'): ObservationComponent | undefined;
    public getDiastolicBP(): Observation_bp_Component_DiastolicBPSliceFlat | undefined;
    public getDiastolicBP (mode: 'flat' | 'raw' = 'flat'): Observation_bp_Component_DiastolicBPSliceFlat | ObservationComponent | undefined {
        const match = observation_bpProfile.DiastolicBPSliceMatch
        const item = getArraySlice(this.resource.component, match)
        if (!item) return undefined
        if (mode === 'raw') return item
        return unwrapSliceChoice<Observation_bp_Component_DiastolicBPSliceFlat>(item, ["code"], "valueQuantity")
    }

    // Validation
    validate(): { errors: string[]; warnings: string[] } {
        const profileName = "observation-bp"
        const res = this.resource
        return {
            errors: [
                ...validateRequired(res, profileName, "status"),
                ...validateEnum(res, profileName, "status", ["registered","preliminary","final","amended","corrected","cancelled","entered-in-error","unknown"]),
                ...validateRequired(res, profileName, "category"),
                ...validateSliceCardinality(res, profileName, "category", {"coding":{"code":"vital-signs","system":"http://terminology.hl7.org/CodeSystem/observation-category"}}, "VSCat", 1, 1),
                ...validateRequired(res, profileName, "code"),
                ...validateFixedValue(res, profileName, "code", {"coding":[{"code":"85354-9","system":"http://loinc.org"}]}),
                ...validateRequired(res, profileName, "subject"),
                ...validateReference(res, profileName, "subject", ["Patient"]),
                ...validateChoiceRequired(res, profileName, ["effectiveDateTime","effectivePeriod"]),
                ...validateReference(res, profileName, "hasMember", ["MolecularSequence","QuestionnaireResponse","Observation"]),
                ...validateReference(res, profileName, "derivedFrom", ["DocumentReference","ImagingStudy","Media","MolecularSequence","QuestionnaireResponse","Observation"]),
                ...validateSliceCardinality(res, profileName, "component", {"code":{"coding":{"code":"8480-6","system":"http://loinc.org"}}}, "SystolicBP", 1, 1),
                ...validateSliceCardinality(res, profileName, "component", {"code":{"coding":{"code":"8462-4","system":"http://loinc.org"}}}, "DiastolicBP", 1, 1),
            ],
            warnings: [
                ...validateEnum(res, profileName, "category", ["social-history","vital-signs","imaging","laboratory","procedure","survey","exam","therapy","activity"]),
                ...validateEnum(res, profileName, "code", ["85353-1","9279-1","8867-4","2708-6","8310-5","8302-2","9843-4","29463-7","39156-5","85354-9","8480-6","8462-4","8478-0"]),
                ...validateEnum(res, profileName, "dataAbsentReason", ["unknown","asked-unknown","temp-unknown","not-asked","asked-declined","masked","not-applicable","unsupported","as-text","error","not-a-number","negative-infinity","positive-infinity","not-performed","not-permitted"]),
                ...validateMustSupport(res, profileName, "dataAbsentReason"),
            ],
        }
    }

}

