// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { Attachment } from "../hl7-fhir-r4-core/Attachment";
import type { Element } from "../hl7-fhir-r4-core/Element";

export type { Attachment } from "../hl7-fhir-r4-core/Attachment";
export type { Element } from "../hl7-fhir-r4-core/Element";

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/RelatedArtifact (pkg: hl7.fhir.r4.core#4.0.1)
export interface RelatedArtifact extends Element {
    citation?: string;
    display?: string;
    document?: Attachment;
    label?: string;
    resource?: string;
    type: ("documentation" | "justification" | "citation" | "predecessor" | "successor" | "derived-from" | "depends-on" | "composed-of");
    url?: string;
}
