// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { Element } from "../hl7-fhir-r4-core/Element";
import type { Quantity } from "../hl7-fhir-r4-core/Quantity";

export type { Element } from "../hl7-fhir-r4-core/Element";
export type { Quantity } from "../hl7-fhir-r4-core/Quantity";

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/SampledData (pkg: hl7.fhir.r4.core#4.0.1)
export interface SampledData extends Element {
    data?: string;
    dimensions: number;
    factor?: number;
    lowerLimit?: number;
    origin: Quantity;
    period: number;
    upperLimit?: number;
}
