// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { BackboneElement } from "../hl7-fhir-r4-core/BackboneElement";
import type { CodeableConcept } from "../hl7-fhir-r4-core/CodeableConcept";
import type { Coding } from "../hl7-fhir-r4-core/Coding";
import type { ContactDetail } from "../hl7-fhir-r4-core/ContactDetail";
import type { DomainResource } from "../hl7-fhir-r4-core/DomainResource";
import type { ElementDefinition } from "../hl7-fhir-r4-core/ElementDefinition";
import type { Identifier } from "../hl7-fhir-r4-core/Identifier";
import type { UsageContext } from "../hl7-fhir-r4-core/UsageContext";

export type { BackboneElement } from "../hl7-fhir-r4-core/BackboneElement";
export type { CodeableConcept } from "../hl7-fhir-r4-core/CodeableConcept";
export type { Coding } from "../hl7-fhir-r4-core/Coding";
export type { ContactDetail } from "../hl7-fhir-r4-core/ContactDetail";
export type { ElementDefinition } from "../hl7-fhir-r4-core/ElementDefinition";
export type { Identifier } from "../hl7-fhir-r4-core/Identifier";
export type { UsageContext } from "../hl7-fhir-r4-core/UsageContext";

export interface StructureDefinitionContext extends BackboneElement {
    expression: string;
    type: ("fhirpath" | "element" | "extension");
}

export interface StructureDefinitionDifferential extends BackboneElement {
    element: ElementDefinition[];
}

export interface StructureDefinitionMapping extends BackboneElement {
    comment?: string;
    identity: string;
    name?: string;
    uri?: string;
}

export interface StructureDefinitionSnapshot extends BackboneElement {
    element: ElementDefinition[];
}

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/StructureDefinition (pkg: hl7.fhir.r4.core#4.0.1)
export interface StructureDefinition extends DomainResource {
    resourceType: "StructureDefinition";

    abstract: boolean;
    baseDefinition?: string;
    contact?: ContactDetail[];
    context?: StructureDefinitionContext[];
    contextInvariant?: string[];
    copyright?: string;
    date?: string;
    derivation?: ("specialization" | "constraint");
    description?: string;
    differential?: StructureDefinitionDifferential;
    experimental?: boolean;
    fhirVersion?: ("0.01" | "0.05" | "0.06" | "0.11" | "0.0.80" | "0.0.81" | "0.0.82" | "0.4.0" | "0.5.0" | "1.0.0" | "1.0.1" | "1.0.2" | "1.1.0" | "1.4.0" | "1.6.0" | "1.8.0" | "3.0.0" | "3.0.1" | "3.3.0" | "3.5.0" | "4.0.0" | "4.0.1");
    identifier?: Identifier[];
    jurisdiction?: CodeableConcept[];
    keyword?: Coding<("fhir-structure" | "custom-resource" | "dam" | "wire-format" | "archetype" | "template" | string)>[];
    kind: ("primitive-type" | "complex-type" | "resource" | "logical");
    mapping?: StructureDefinitionMapping[];
    name: string;
    publisher?: string;
    purpose?: string;
    snapshot?: StructureDefinitionSnapshot;
    status: ("draft" | "active" | "retired" | "unknown");
    title?: string;
    type: string;
    url: string;
    useContext?: UsageContext[];
    version?: string;
}
export const isStructureDefinition = (resource: unknown): resource is StructureDefinition => {
    return resource !== null && typeof resource === "object" && (resource as {resourceType: string}).resourceType === "StructureDefinition";
}
