// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { Coding } from "../../hl7-fhir-r4-core/Coding";
import type { Extension } from "../../hl7-fhir-r4-core/Extension";

import {
    buildResource,
    validateRequired,
    validateExcluded,
    validateFixedValue,
    validateSliceCardinality,
    validateEnum,
    validateReference,
    validateChoiceRequired,
    validateMustSupport,
} from "../../profile-helpers";

export type USCoreIndividualSexExtensionProfileRaw = {
    valueCoding: Coding;
}

// CanonicalURL: http://hl7.org/fhir/us/core/StructureDefinition/us-core-individual-sex (pkg: hl7.fhir.us.core#8.0.1)
export class USCoreIndividualSexExtensionProfile {
    static readonly canonicalUrl = "http://hl7.org/fhir/us/core/StructureDefinition/us-core-individual-sex";

    private resource: Extension;

    constructor (resource: Extension) {
        this.resource = resource;
    }

    static from (resource: Extension) : USCoreIndividualSexExtensionProfile {
        const profile = new USCoreIndividualSexExtensionProfile(resource);
        const { errors } = profile.validate();
        if (errors.length > 0) throw new Error(errors.join("; "))
        return profile;
    }

    static apply (resource: Extension) : USCoreIndividualSexExtensionProfile {
        return new USCoreIndividualSexExtensionProfile(resource);
    }

    static createResource (args: USCoreIndividualSexExtensionProfileRaw) : Extension {
        const resource = buildResource<Extension>( {
            url: "http://hl7.org/fhir/us/core/StructureDefinition/us-core-individual-sex",
            valueCoding: args.valueCoding,
        })
        return resource;
    }

    static create (args: USCoreIndividualSexExtensionProfileRaw) : USCoreIndividualSexExtensionProfile {
        return USCoreIndividualSexExtensionProfile.apply(USCoreIndividualSexExtensionProfile.createResource(args));
    }

    toResource () : Extension {
        return this.resource;
    }

    // Field accessors
    getValueCoding () : Coding | undefined {
        return this.resource.valueCoding as Coding | undefined;
    }

    setValueCoding (value: Coding) : this {
        Object.assign(this.resource, { valueCoding: value });
        return this;
    }

    getUrl () : string | undefined {
        return this.resource.url as string | undefined;
    }

    setUrl (value: string) : this {
        Object.assign(this.resource, { url: value });
        return this;
    }

    // Extensions
    // Slices
    // Validation
    validate(): { errors: string[]; warnings: string[] } {
        const profileName = "USCoreIndividualSexExtension"
        const res = this.resource
        return {
            errors: [
                ...validateRequired(res, profileName, "url"),
                ...validateFixedValue(res, profileName, "url", USCoreIndividualSexExtensionProfile.canonicalUrl),
                ...validateChoiceRequired(res, profileName, ["valueCoding"]),
            ],
            warnings: [],
        }
    }

}

