# WARNING: This file is autogenerated by @atomic-ehr/codegen.
# GitHub: https://github.com/atomic-ehr/codegen
# Any manual changes made to this file may be overwritten.

from __future__ import annotations
from pydantic import BaseModel, ConfigDict, Field, PositiveInt
from typing import Generic, List as PyList, Literal
from typing_extensions import TypeVar

T = TypeVar('T', bound=str, default=str)


class Element(BaseModel):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    extension: PyList[Extension] | None = Field(None, alias="extension", serialization_alias="extension")
    id: str | None = Field(None, alias="id", serialization_alias="id")


class Address(Element):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    city: str | None = Field(None, alias="city", serialization_alias="city")
    country: str | None = Field(None, alias="country", serialization_alias="country")
    district: str | None = Field(None, alias="district", serialization_alias="district")
    line: PyList[str] | None = Field(None, alias="line", serialization_alias="line")
    period: Period | None = Field(None, alias="period", serialization_alias="period")
    postal_code: str | None = Field(None, alias="postalCode", serialization_alias="postalCode")
    state: str | None = Field(None, alias="state", serialization_alias="state")
    text: str | None = Field(None, alias="text", serialization_alias="text")
    type: Literal["postal", "physical", "both"] | None = Field(None, alias="type", serialization_alias="type")
    use: Literal["home", "work", "temp", "old", "billing"] | None = Field(None, alias="use", serialization_alias="use")


class Quantity(Element):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    code: str | None = Field(None, alias="code", serialization_alias="code")
    comparator: Literal["<", "<=", ">=", ">"] | None = Field(None, alias="comparator", serialization_alias="comparator")
    system: str | None = Field(None, alias="system", serialization_alias="system")
    unit: str | None = Field(None, alias="unit", serialization_alias="unit")
    value: float | None = Field(None, alias="value", serialization_alias="value")


class Age(Quantity):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    pass


class Annotation(Element):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    author_reference: Reference | None = Field(None, alias="authorReference", serialization_alias="authorReference")
    author_string: str | None = Field(None, alias="authorString", serialization_alias="authorString")
    text: str = Field(alias="text", serialization_alias="text")
    time: str | None = Field(None, alias="time", serialization_alias="time")


class Attachment(Element):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    content_type: str | None = Field(None, alias="contentType", serialization_alias="contentType")
    creation: str | None = Field(None, alias="creation", serialization_alias="creation")
    data: str | None = Field(None, alias="data", serialization_alias="data")
    hash: str | None = Field(None, alias="hash", serialization_alias="hash")
    language: str | None = Field(None, alias="language", serialization_alias="language")
    size: int | None = Field(None, alias="size", serialization_alias="size")
    title: str | None = Field(None, alias="title", serialization_alias="title")
    url: str | None = Field(None, alias="url", serialization_alias="url")


class BackboneElement(Element):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")


class CodeableConcept(Element, Generic[T]):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    coding: PyList[Coding[T]] | None = Field(None, alias="coding", serialization_alias="coding")
    text: str | None = Field(None, alias="text", serialization_alias="text")


class Coding(Element, Generic[T]):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    code: T | None = Field(None, alias="code", serialization_alias="code")
    display: str | None = Field(None, alias="display", serialization_alias="display")
    system: str | None = Field(None, alias="system", serialization_alias="system")
    user_selected: bool | None = Field(None, alias="userSelected", serialization_alias="userSelected")
    version: str | None = Field(None, alias="version", serialization_alias="version")


class ContactDetail(Element):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    name: str | None = Field(None, alias="name", serialization_alias="name")
    telecom: PyList[ContactPoint] | None = Field(None, alias="telecom", serialization_alias="telecom")


class ContactPoint(Element):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    period: Period | None = Field(None, alias="period", serialization_alias="period")
    rank: PositiveInt | None = Field(None, alias="rank", serialization_alias="rank")
    system: Literal["phone", "fax", "email", "pager", "url", "sms", "other"] | None = Field(None, alias="system", serialization_alias="system")
    use: Literal["home", "work", "temp", "old", "mobile"] | None = Field(None, alias="use", serialization_alias="use")
    value: str | None = Field(None, alias="value", serialization_alias="value")


class Contributor(Element):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    contact: PyList[ContactDetail] | None = Field(None, alias="contact", serialization_alias="contact")
    name: str = Field(alias="name", serialization_alias="name")
    type: Literal["author", "editor", "reviewer", "endorser"] = Field(alias="type", serialization_alias="type")


class Count(Quantity):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    pass


class DataRequirementCodeFilter(Element):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    code: PyList[Coding] | None = Field(None, alias="code", serialization_alias="code")
    path: str | None = Field(None, alias="path", serialization_alias="path")
    search_param: str | None = Field(None, alias="searchParam", serialization_alias="searchParam")
    value_set: str | None = Field(None, alias="valueSet", serialization_alias="valueSet")

class DataRequirementDateFilter(Element):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    path: str | None = Field(None, alias="path", serialization_alias="path")
    search_param: str | None = Field(None, alias="searchParam", serialization_alias="searchParam")
    value_date_time: str | None = Field(None, alias="valueDateTime", serialization_alias="valueDateTime")
    value_duration: Duration | None = Field(None, alias="valueDuration", serialization_alias="valueDuration")
    value_period: Period | None = Field(None, alias="valuePeriod", serialization_alias="valuePeriod")

class DataRequirementSort(Element):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    direction: Literal["ascending", "descending"] = Field(alias="direction", serialization_alias="direction")
    path: str = Field(alias="path", serialization_alias="path")


class DataRequirement(Element):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    code_filter: PyList[DataRequirementCodeFilter] | None = Field(None, alias="codeFilter", serialization_alias="codeFilter")
    date_filter: PyList[DataRequirementDateFilter] | None = Field(None, alias="dateFilter", serialization_alias="dateFilter")
    limit: PositiveInt | None = Field(None, alias="limit", serialization_alias="limit")
    must_support: PyList[str] | None = Field(None, alias="mustSupport", serialization_alias="mustSupport")
    profile: PyList[str] | None = Field(None, alias="profile", serialization_alias="profile")
    sort: PyList[DataRequirementSort] | None = Field(None, alias="sort", serialization_alias="sort")
    subject_codeable_concept: CodeableConcept | None = Field(None, alias="subjectCodeableConcept", serialization_alias="subjectCodeableConcept")
    subject_reference: Reference | None = Field(None, alias="subjectReference", serialization_alias="subjectReference")
    type: str = Field(alias="type", serialization_alias="type")


class Distance(Quantity):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    pass


class DosageDoseAndRate(Element):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    dose_quantity: Quantity | None = Field(None, alias="doseQuantity", serialization_alias="doseQuantity")
    dose_range: Range | None = Field(None, alias="doseRange", serialization_alias="doseRange")
    rate_quantity: Quantity | None = Field(None, alias="rateQuantity", serialization_alias="rateQuantity")
    rate_range: Range | None = Field(None, alias="rateRange", serialization_alias="rateRange")
    rate_ratio: Ratio | None = Field(None, alias="rateRatio", serialization_alias="rateRatio")
    type: CodeableConcept | None = Field(None, alias="type", serialization_alias="type")


class Dosage(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    additional_instruction: PyList[CodeableConcept] | None = Field(None, alias="additionalInstruction", serialization_alias="additionalInstruction")
    as_needed_boolean: bool | None = Field(None, alias="asNeededBoolean", serialization_alias="asNeededBoolean")
    as_needed_codeable_concept: CodeableConcept | None = Field(None, alias="asNeededCodeableConcept", serialization_alias="asNeededCodeableConcept")
    dose_and_rate: PyList[DosageDoseAndRate] | None = Field(None, alias="doseAndRate", serialization_alias="doseAndRate")
    max_dose_per_administration: Quantity | None = Field(None, alias="maxDosePerAdministration", serialization_alias="maxDosePerAdministration")
    max_dose_per_lifetime: Quantity | None = Field(None, alias="maxDosePerLifetime", serialization_alias="maxDosePerLifetime")
    max_dose_per_period: Ratio | None = Field(None, alias="maxDosePerPeriod", serialization_alias="maxDosePerPeriod")
    method: CodeableConcept | None = Field(None, alias="method", serialization_alias="method")
    patient_instruction: str | None = Field(None, alias="patientInstruction", serialization_alias="patientInstruction")
    route: CodeableConcept | None = Field(None, alias="route", serialization_alias="route")
    sequence: int | None = Field(None, alias="sequence", serialization_alias="sequence")
    site: CodeableConcept | None = Field(None, alias="site", serialization_alias="site")
    text: str | None = Field(None, alias="text", serialization_alias="text")
    timing: Timing | None = Field(None, alias="timing", serialization_alias="timing")


class Duration(Quantity):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    pass


class Expression(Element):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    description: str | None = Field(None, alias="description", serialization_alias="description")
    expression: str | None = Field(None, alias="expression", serialization_alias="expression")
    language: str = Field(alias="language", serialization_alias="language")
    name: str | None = Field(None, alias="name", serialization_alias="name")
    reference: str | None = Field(None, alias="reference", serialization_alias="reference")


class Extension(Element):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    url: str = Field(alias="url", serialization_alias="url")
    value_address: Address | None = Field(None, alias="valueAddress", serialization_alias="valueAddress")
    value_age: Age | None = Field(None, alias="valueAge", serialization_alias="valueAge")
    value_annotation: Annotation | None = Field(None, alias="valueAnnotation", serialization_alias="valueAnnotation")
    value_attachment: Attachment | None = Field(None, alias="valueAttachment", serialization_alias="valueAttachment")
    value_base64binary: str | None = Field(None, alias="valueBase64Binary", serialization_alias="valueBase64Binary")
    value_boolean: bool | None = Field(None, alias="valueBoolean", serialization_alias="valueBoolean")
    value_canonical: str | None = Field(None, alias="valueCanonical", serialization_alias="valueCanonical")
    value_code: str | None = Field(None, alias="valueCode", serialization_alias="valueCode")
    value_codeable_concept: CodeableConcept | None = Field(None, alias="valueCodeableConcept", serialization_alias="valueCodeableConcept")
    value_coding: Coding | None = Field(None, alias="valueCoding", serialization_alias="valueCoding")
    value_contact_detail: ContactDetail | None = Field(None, alias="valueContactDetail", serialization_alias="valueContactDetail")
    value_contact_point: ContactPoint | None = Field(None, alias="valueContactPoint", serialization_alias="valueContactPoint")
    value_contributor: Contributor | None = Field(None, alias="valueContributor", serialization_alias="valueContributor")
    value_count: Count | None = Field(None, alias="valueCount", serialization_alias="valueCount")
    value_data_requirement: DataRequirement | None = Field(None, alias="valueDataRequirement", serialization_alias="valueDataRequirement")
    value_date: str | None = Field(None, alias="valueDate", serialization_alias="valueDate")
    value_date_time: str | None = Field(None, alias="valueDateTime", serialization_alias="valueDateTime")
    value_decimal: float | None = Field(None, alias="valueDecimal", serialization_alias="valueDecimal")
    value_distance: Distance | None = Field(None, alias="valueDistance", serialization_alias="valueDistance")
    value_dosage: Dosage | None = Field(None, alias="valueDosage", serialization_alias="valueDosage")
    value_duration: Duration | None = Field(None, alias="valueDuration", serialization_alias="valueDuration")
    value_expression: Expression | None = Field(None, alias="valueExpression", serialization_alias="valueExpression")
    value_human_name: HumanName | None = Field(None, alias="valueHumanName", serialization_alias="valueHumanName")
    value_id: str | None = Field(None, alias="valueId", serialization_alias="valueId")
    value_identifier: Identifier | None = Field(None, alias="valueIdentifier", serialization_alias="valueIdentifier")
    value_instant: str | None = Field(None, alias="valueInstant", serialization_alias="valueInstant")
    value_integer: int | None = Field(None, alias="valueInteger", serialization_alias="valueInteger")
    value_markdown: str | None = Field(None, alias="valueMarkdown", serialization_alias="valueMarkdown")
    value_meta: Meta | None = Field(None, alias="valueMeta", serialization_alias="valueMeta")
    value_money: Money | None = Field(None, alias="valueMoney", serialization_alias="valueMoney")
    value_oid: str | None = Field(None, alias="valueOid", serialization_alias="valueOid")
    value_parameter_definition: ParameterDefinition | None = Field(None, alias="valueParameterDefinition", serialization_alias="valueParameterDefinition")
    value_period: Period | None = Field(None, alias="valuePeriod", serialization_alias="valuePeriod")
    value_positive_int: PositiveInt | None = Field(None, alias="valuePositiveInt", serialization_alias="valuePositiveInt")
    value_quantity: Quantity | None = Field(None, alias="valueQuantity", serialization_alias="valueQuantity")
    value_range: Range | None = Field(None, alias="valueRange", serialization_alias="valueRange")
    value_ratio: Ratio | None = Field(None, alias="valueRatio", serialization_alias="valueRatio")
    value_reference: Reference | None = Field(None, alias="valueReference", serialization_alias="valueReference")
    value_related_artifact: RelatedArtifact | None = Field(None, alias="valueRelatedArtifact", serialization_alias="valueRelatedArtifact")
    value_sampled_data: SampledData | None = Field(None, alias="valueSampledData", serialization_alias="valueSampledData")
    value_signature: Signature | None = Field(None, alias="valueSignature", serialization_alias="valueSignature")
    value_string: str | None = Field(None, alias="valueString", serialization_alias="valueString")
    value_time: str | None = Field(None, alias="valueTime", serialization_alias="valueTime")
    value_timing: Timing | None = Field(None, alias="valueTiming", serialization_alias="valueTiming")
    value_trigger_definition: TriggerDefinition | None = Field(None, alias="valueTriggerDefinition", serialization_alias="valueTriggerDefinition")
    value_unsigned_int: int | None = Field(None, alias="valueUnsignedInt", serialization_alias="valueUnsignedInt")
    value_uri: str | None = Field(None, alias="valueUri", serialization_alias="valueUri")
    value_url: str | None = Field(None, alias="valueUrl", serialization_alias="valueUrl")
    value_usage_context: UsageContext | None = Field(None, alias="valueUsageContext", serialization_alias="valueUsageContext")
    value_uuid: str | None = Field(None, alias="valueUuid", serialization_alias="valueUuid")


class HumanName(Element):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    family: str | None = Field(None, alias="family", serialization_alias="family")
    given: PyList[str] | None = Field(None, alias="given", serialization_alias="given")
    period: Period | None = Field(None, alias="period", serialization_alias="period")
    prefix: PyList[str] | None = Field(None, alias="prefix", serialization_alias="prefix")
    suffix: PyList[str] | None = Field(None, alias="suffix", serialization_alias="suffix")
    text: str | None = Field(None, alias="text", serialization_alias="text")
    use: Literal["usual", "official", "temp", "nickname", "anonymous", "old", "maiden"] | None = Field(None, alias="use", serialization_alias="use")


class Identifier(Element):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    assigner: Reference | None = Field(None, alias="assigner", serialization_alias="assigner")
    period: Period | None = Field(None, alias="period", serialization_alias="period")
    system: str | None = Field(None, alias="system", serialization_alias="system")
    type: CodeableConcept[Literal["DL", "PPN", "BRN", "MR", "MCN", "EN", "TAX", "NIIP", "PRN", "MD", "DR", "ACSN", "UDI", "SNO", "SB", "PLAC", "FILL", "JHN"] | str] | None = Field(None, alias="type", serialization_alias="type")
    use: Literal["usual", "official", "temp", "secondary", "old"] | None = Field(None, alias="use", serialization_alias="use")
    value: str | None = Field(None, alias="value", serialization_alias="value")


class Meta(Element):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    last_updated: str | None = Field(None, alias="lastUpdated", serialization_alias="lastUpdated")
    profile: PyList[str] | None = Field(None, alias="profile", serialization_alias="profile")
    security: PyList[Coding] | None = Field(None, alias="security", serialization_alias="security")
    source: str | None = Field(None, alias="source", serialization_alias="source")
    tag: PyList[Coding] | None = Field(None, alias="tag", serialization_alias="tag")
    version_id: str | None = Field(None, alias="versionId", serialization_alias="versionId")


class Money(Element):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    currency: str | None = Field(None, alias="currency", serialization_alias="currency")
    value: float | None = Field(None, alias="value", serialization_alias="value")


class Narrative(Element):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    div: str = Field(alias="div", serialization_alias="div")
    status: Literal["generated", "extensions", "additional", "empty"] = Field(alias="status", serialization_alias="status")


class ParameterDefinition(Element):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    documentation: str | None = Field(None, alias="documentation", serialization_alias="documentation")
    max: str | None = Field(None, alias="max", serialization_alias="max")
    min: int | None = Field(None, alias="min", serialization_alias="min")
    name: str | None = Field(None, alias="name", serialization_alias="name")
    profile: str | None = Field(None, alias="profile", serialization_alias="profile")
    type: str = Field(alias="type", serialization_alias="type")
    use: Literal["in", "out"] = Field(alias="use", serialization_alias="use")


class Period(Element):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    end: str | None = Field(None, alias="end", serialization_alias="end")
    start: str | None = Field(None, alias="start", serialization_alias="start")


class Range(Element):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    high: Quantity | None = Field(None, alias="high", serialization_alias="high")
    low: Quantity | None = Field(None, alias="low", serialization_alias="low")


class Ratio(Element):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    denominator: Quantity | None = Field(None, alias="denominator", serialization_alias="denominator")
    numerator: Quantity | None = Field(None, alias="numerator", serialization_alias="numerator")


class Reference(Element):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    display: str | None = Field(None, alias="display", serialization_alias="display")
    identifier: Identifier | None = Field(None, alias="identifier", serialization_alias="identifier")
    reference: str | None = Field(None, alias="reference", serialization_alias="reference")
    type: str | None = Field(None, alias="type", serialization_alias="type")


class RelatedArtifact(Element):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    citation: str | None = Field(None, alias="citation", serialization_alias="citation")
    display: str | None = Field(None, alias="display", serialization_alias="display")
    document: Attachment | None = Field(None, alias="document", serialization_alias="document")
    label: str | None = Field(None, alias="label", serialization_alias="label")
    resource: str | None = Field(None, alias="resource", serialization_alias="resource")
    type: Literal["documentation", "justification", "citation", "predecessor", "successor", "derived-from", "depends-on", "composed-of"] = Field(alias="type", serialization_alias="type")
    url: str | None = Field(None, alias="url", serialization_alias="url")


class SampledData(Element):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    data: str | None = Field(None, alias="data", serialization_alias="data")
    dimensions: PositiveInt = Field(alias="dimensions", serialization_alias="dimensions")
    factor: float | None = Field(None, alias="factor", serialization_alias="factor")
    lower_limit: float | None = Field(None, alias="lowerLimit", serialization_alias="lowerLimit")
    origin: Quantity = Field(alias="origin", serialization_alias="origin")
    period: float = Field(alias="period", serialization_alias="period")
    upper_limit: float | None = Field(None, alias="upperLimit", serialization_alias="upperLimit")


class Signature(Element):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    data: str | None = Field(None, alias="data", serialization_alias="data")
    on_behalf_of: Reference | None = Field(None, alias="onBehalfOf", serialization_alias="onBehalfOf")
    sig_format: str | None = Field(None, alias="sigFormat", serialization_alias="sigFormat")
    target_format: str | None = Field(None, alias="targetFormat", serialization_alias="targetFormat")
    type: PyList[Coding[Literal["1.2.840.10065.1.12.1.1", "1.2.840.10065.1.12.1.2", "1.2.840.10065.1.12.1.3", "1.2.840.10065.1.12.1.4", "1.2.840.10065.1.12.1.5", "1.2.840.10065.1.12.1.6", "1.2.840.10065.1.12.1.7", "1.2.840.10065.1.12.1.8", "1.2.840.10065.1.12.1.9", "1.2.840.10065.1.12.1.10", "1.2.840.10065.1.12.1.11", "1.2.840.10065.1.12.1.12", "1.2.840.10065.1.12.1.13", "1.2.840.10065.1.12.1.14", "1.2.840.10065.1.12.1.15", "1.2.840.10065.1.12.1.16", "1.2.840.10065.1.12.1.17", "1.2.840.10065.1.12.1.18"] | str]] = Field(alias="type", serialization_alias="type")
    when: str = Field(alias="when", serialization_alias="when")
    who: Reference = Field(alias="who", serialization_alias="who")


class TimingRepeat(Element):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    bounds_duration: Duration | None = Field(None, alias="boundsDuration", serialization_alias="boundsDuration")
    bounds_period: Period | None = Field(None, alias="boundsPeriod", serialization_alias="boundsPeriod")
    bounds_range: Range | None = Field(None, alias="boundsRange", serialization_alias="boundsRange")
    count: PositiveInt | None = Field(None, alias="count", serialization_alias="count")
    count_max: PositiveInt | None = Field(None, alias="countMax", serialization_alias="countMax")
    day_of_week: PyList[Literal["mon", "tue", "wed", "thu", "fri", "sat", "sun"]] | None = Field(None, alias="dayOfWeek", serialization_alias="dayOfWeek")
    duration: float | None = Field(None, alias="duration", serialization_alias="duration")
    duration_max: float | None = Field(None, alias="durationMax", serialization_alias="durationMax")
    duration_unit: Literal["s", "min", "h", "d", "wk", "mo", "a"] | None = Field(None, alias="durationUnit", serialization_alias="durationUnit")
    frequency: PositiveInt | None = Field(None, alias="frequency", serialization_alias="frequency")
    frequency_max: PositiveInt | None = Field(None, alias="frequencyMax", serialization_alias="frequencyMax")
    offset: int | None = Field(None, alias="offset", serialization_alias="offset")
    period: float | None = Field(None, alias="period", serialization_alias="period")
    period_max: float | None = Field(None, alias="periodMax", serialization_alias="periodMax")
    period_unit: Literal["s", "min", "h", "d", "wk", "mo", "a"] | None = Field(None, alias="periodUnit", serialization_alias="periodUnit")
    time_of_day: PyList[str] | None = Field(None, alias="timeOfDay", serialization_alias="timeOfDay")
    when: PyList[Literal["MORN", "MORN.early", "MORN.late", "NOON", "AFT", "AFT.early", "AFT.late", "EVE", "EVE.early", "EVE.late", "NIGHT", "PHS", "HS", "WAKE", "C", "CM", "CD", "CV", "AC", "ACM", "ACD", "ACV", "PC", "PCM", "PCD", "PCV"]] | None = Field(None, alias="when", serialization_alias="when")


class Timing(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    code: CodeableConcept[Literal["BID", "TID", "QID", "AM", "PM", "QD", "QOD", "Q1H", "Q2H", "Q3H", "Q4H", "Q6H", "Q8H", "BED", "WK", "MO"] | str] | None = Field(None, alias="code", serialization_alias="code")
    event: PyList[str] | None = Field(None, alias="event", serialization_alias="event")
    repeat: TimingRepeat | None = Field(None, alias="repeat", serialization_alias="repeat")


class TriggerDefinition(Element):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    condition: Expression | None = Field(None, alias="condition", serialization_alias="condition")
    data: PyList[DataRequirement] | None = Field(None, alias="data", serialization_alias="data")
    name: str | None = Field(None, alias="name", serialization_alias="name")
    timing_date: str | None = Field(None, alias="timingDate", serialization_alias="timingDate")
    timing_date_time: str | None = Field(None, alias="timingDateTime", serialization_alias="timingDateTime")
    timing_reference: Reference | None = Field(None, alias="timingReference", serialization_alias="timingReference")
    timing_timing: Timing | None = Field(None, alias="timingTiming", serialization_alias="timingTiming")
    type: Literal["named-event", "periodic", "data-changed", "data-added", "data-modified", "data-removed", "data-accessed", "data-access-ended"] = Field(alias="type", serialization_alias="type")


class UsageContext(Element):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    code: Coding[Literal["gender", "age", "focus", "user", "workflow", "task", "venue", "species", "program"] | str] = Field(alias="code", serialization_alias="code")
    value_codeable_concept: CodeableConcept | None = Field(None, alias="valueCodeableConcept", serialization_alias="valueCodeableConcept")
    value_quantity: Quantity | None = Field(None, alias="valueQuantity", serialization_alias="valueQuantity")
    value_range: Range | None = Field(None, alias="valueRange", serialization_alias="valueRange")
    value_reference: Reference | None = Field(None, alias="valueReference", serialization_alias="valueReference")


